//
//  Extension+Images.swift
//  Sportified
//
//  Created by Tariq Mahmood   on 01/05/2024.
//

import SwiftUI
extension Image{
    
    static let ic_appLogo = Image("ic_appLogo")
    static let img_Location = Image("img_Location")
    static let img_onbording1 = Image("img_onbording1")
    static let img_onbording2 = Image("img_onbording2")
    static let ic_arrow = Image("ic_arrow")
    static let ic_Google = Image("ic_Google")
    static let ic_Calander = Image("ic_Calander")
    static let ic_copy = Image("ic_copy")
    static let ic_clock = Image("ic_clock")
    static let ic_arrowDown = Image("ic_arrowDown")
    static let img_OTP = Image("img_OTP")
    static let ic_add = Image("ic_add")
    static let ic_vs = Image("ic_vs")
    static let img_User = Image("img_User")
    static let ic_Location = Image("ic_Location")
    static let ic_comm = Image("ic_comm")
    static let ic_bell = Image("ic_bell")
    static let ic_arrowDownBlck = Image("ic_arrowDownBlck")
    static let ic_User = Image("ic_User")
    static let img_Slider = Image("img_Slider")
    static let ic_ArrowBack = Image("ic_ArrowBack")
    static let ic_Share = Image("ic_Share")
    static let ic_Men = Image("ic_Men")
    static let ic_Filter = Image("ic_Filter")
    static let ic_Sort = Image("ic_Sort")
    static let ic_BellWight = Image("ic_BellWight")
    static let ic_ArrowDownWight = Image("ic_ArrowDownWight")
    static let ic_Plus = Image("ic_Plus")
    static let account_Fill = Image("account_Fill")
    static let ic_MyGame = Image("ic_MyGame")
    static let ic_Chat = Image("ic_Chat")
    static let ic_Term = Image("ic_Term")
    static let ic_BellGreen = Image("ic_BellGreen")
    static let ic_LogOut = Image("ic_LogOut")
    static let ic_MatchesSrore = Image("ic_MatchesSrore")
    static let ic_Pre = Image("ic_Pre")
    static let ic_Loc = Image("ic_Loc")
    static let ic_Lock = Image("ic_Lock")
    static let ic_World = Image("ic_World")
    static let ic_camra = Image("ic_camra")
    static let ic_edit = Image("ic_edit")
    static let ic_SwitchOn = Image("ic_SwitchOn")
    static let ic_Cha = Image("ic_Cha")
    static let ic_Adme = Image("ic_Adme")
    static let ic_Arrw = Image("ic_Arrw")
    static let ic_FindUsers = Image("ic_FindUsers")
    static let ic_Search = Image("ic_Search")
    static let ic_addwight = Image("ic_addwight")
    static let ic_Tick = Image("ic_Tick")
    static let ic_profile = Image("ic_profile")
    static let ic_SendSMS = Image("ic_SendSMS")
    static let ic_World_b = Image("ic_World_b")
    static let ic_Lock_W = Image("ic_Lock_W")
    static let ic_addPlayer = Image("ic_addPlayer")
}
